### ISSUE TITLE
OSACA can't parse memory operand without base

### ISSUE THREAD

**Issue by ychen306** [RRZE-HPC/OSACA#29]
E.g. `lea (,%rax,8), %rbx`.

**Comment by JanLJL** [comment]
Since we are rewriting the parser from scratch for a new OSACA version, this issue won't be fixed until the release of it (probably 0.3.0) due to too much effort, sorry for any inconvenience until then.
If you analyze a rather small kernel, I recommend you to add a base register for your instruction forms in the code manually, so the parser will accept it for further processing.

Nevertheless, we will take this and other issues into account for the new version, so thank you for pointing it out!

**Comment by ychen306** [comment]
Have you considered using Intel's XED library to parse instructions? IIRC it has a python binding.

**Comment by cod3monk** [comment]
solved in new version (dev releases are available)

**Comment by cod3monk** [comment]
> Have you considered using Intel's XED library to parse instructions? IIRC it has a python binding.

we have looked at multiple libraries with python support, but none support multiple ISAs.
