### ISSUE TITLE
OSACA can't parse NOPW

### ISSUE THREAD

**Issue by ychen306** [RRZE-HPC/OSACA#30]
E.g. `nopw %cs:(%rax,%rax)`.

**Comment by JanLJL** [comment]
OSACA can't parse this instruction form because of the `%cs:(%rax,%rax)` addressing (see #31), `nopw` gets parsed normally.
As soon as #31 is resolved, this should work as well.

Since `%cs:(%rax,%rax)` in this case is only used to align code, I recommend you to simply replace it by something else for analyzing the kernel.

**Comment by JanLJL** [comment]
Closed because of duplicate (#31 )
