### ISSUE TITLE
OSACA can't parse instructions that read from TLS

### ISSUE THREAD

**Issue by ychen306** [RRZE-HPC/OSACA#31]
E.g. `movl %fs:40, %eax`

**Comment by JanLJL** [comment]
Since we are rewriting the parser from scratch for a new OSACA version, this issue won't be fixed until the release of it (probably 0.3.0) due to too much effort, sorry for any inconvenience until then.
Nevertheless, we will take this and other issues into account for the new version, so thank you for pointing it out!

**Comment by cod3monk** [comment]
solved in new version (dev releases are available)
