### ISSUE TITLE
Running OSACA standalone

### ISSUE THREAD

**Issue by travisdowns** [RRZE-HPC/OSACA#38]
I would like to run OSACA standalone, i.e., without first installing it - so I can keep my distribution python clean and so I can try changes quickly. I assume during development that's what you do? Is it possibly/easy?

**Comment by JanLJL** [comment]
I suggest to create a virtual environment with python using `python -m venv /path/to/new/virtual/environment`. For more information see the [python docs](https://docs.python.org/3/library/venv.html#creating-virtual-environments).
This way, you do not interfere with your normal python installation. After activating it, you can both install it manually using `python setup.py install` or via pip using `pip install osaca==[version]` and it only affects your virtual environment.

If you're looking for a simple way during development, I suggest you to run `python setup.py develop` inside of an venv. This installs the module in a way that allows you to conveniently edit your code and have the changes take effect immediately.

I hope this helps, otherwise let me know!

**Comment by travisdowns** [comment]
This helps a lot, thanks.

**Comment by JanLJL** [comment]
Closed for now
