### ISSUE TITLE
Callq *%rax

### ISSUE THREAD

**Issue by partouf** [RRZE-HPC/OSACA#57]
No idea what it means, but the simplest Rust compiler output generates it; https://godbolt.org/z/T9bh3P

Error: `ValueError: Could not parse instruction on line 34: '        callq   *%rax'`

**Comment by JanLJL** [comment]
Hi @partouf,

it seems like the compiler uses the `*%rax` as an absolute jump operand, even though I've also never seen that before without `()` brackets in AT&T syntax.
While testing your code snippet, I realized also the `::` delimiter that is apparently used by the Rust compiler in labels couldn't be recognized (sorry, we don't have many people using Rust in our team, so there might be more problems).
Both issues should be fixed with f9f1120 and 2093610, respectively, and will appear with the next release!
