### ISSUE TITLE
Throughput output

### ISSUE THREAD

**Issue by andreas-abel** [RRZE-HPC/OSACA#63]
IACA's output contains a line that shows the "Block Throughput" of a loop kernel. 

Figure 4 in your paper (https://arxiv.org/pdf/1809.00912.pdf) shows a similar line with the "Total number of estimated throughput".

However, at least the current version of OSACA does not output this information. Is there an option that enables this output, or do you consider the throughput to be the maximum of the numbers in the line under the table in the "Combined Analysis Report"?

**Comment by JanLJL** [comment]
Hi Andreas,

unfortunately, in the command line output there is no overall estimated throughput or runtime as for now.


Since we have introduced the critical path analysis in https://arxiv.org/abs/1910.00214, each analysis gives you three numbers: The throughput number(s) of the kernel (let's say the maximum of all available ports is `TP`), the critical path (`CP`) and the longest loop-carried dependency (`LCD`). We assume the runtime of the kernel to be `max(TP, LCD)`. The CP normally can be neglected and works more as a worst-case upper bound if being larger than the TP and LCD. Of course this can be only done if the CP can be overlapped with the CPs of the other iterations of the loop. This depends on the architecture of the CPU (number of functional units, size of the ROB, number of registers, etc...) and the length and characteristic of the kernel/CP and can only be detected by further (manual) analysis with more insight.

For integration in a different python program/module, I'm happy to provide you with an updated API on top of the existing one if you let me know what you need.

If it is only about getting a single number as runtime prediction in the output and you think it helps you in your work routine, we can also add the above mentioned function of TP and LCD in the command line output.

I will wait with any implementation until hearing back from so you we know what you are looking for.
Best,
Jan

**Comment by andreas-abel** [comment]
Hi Jan,

thanks for the quick reply. Essentially, what I would like to do is to reproduce the numbers in the BHive paper (https://groups.csail.mit.edu/commit/papers/19/ithemal-measurement.pdf). Do you happen to know what they used to obtain the OSACA results? Was it `max(TP, LCD)`?

Regards,
Andreas

**Comment by JanLJL** [comment]
The paper was produced when we were still working on version 0.3, so there was no loop-carried dependency detection yet.
I am not even sure if we already based our data files on your uops.info data, so results would look probably quite different now...
I know @cod3monk had a closer look at their work when it was released and also reproduced (at least parts of) their results.

**Comment by andreas-abel** [comment]
That's fine if the numbers are different now. My goal is to compare different throughput-prediction tools in a similar way as the BHive paper (sorry if my previous comment wasn't completely clear), and I wanted to make sure that I represent OSACA in a fair way.

**Comment by cod3monk** [comment]
> I am not even sure if we already based our data files on your uops.info data, so results would look probably quite different now...
It was not. That paper was part of the reason why we started including all off uops.info into OSACA models, to allow for an easier, wider and less-error-prone application.
